apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
   name: prometheus
spec:
 serviceAccountName: prometheus
 serviceMonitorSelector:
   matchLabels:
     team: broker
 resources:
   requests:
     memory: 200Mi
     cpu: 2