apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: jaeger
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      service: jaeger
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: jaeger
    spec:
      containers:
        - image: jaegertracing/all-in-one:latest
          name: jaeger
          ports:
            - containerPort: 6831
              protocol: UDP
            - containerPort: 16686
            - containerPort: 14268
          resources: {}
      restartPolicy: Always
status: {}