apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: broker
  name: broker-service
spec:
  type: NodePort
  ports:
    - name: "rpc"
      port: 8081
      targetPort: 8081
      nodePort: 32341
  selector:
    app: broker
status:
  loadBalancer: {}