apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: broker
  name: broker-service
spec:
  clusterIP: None
  ports:
    - name: "rpc"
      port: 8081
      targetPort: 8081
  selector:
    app: broker
status:
  loadBalancer: {}