apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: broker
  name: broker-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: broker
status:
  loadBalancer: {}