apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: broker-service
  name: broker
spec:
  type: NodePort
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
    - name: prometheus
      port: 8000
      targetPort: 8000
  selector:
    service: broker
status:
  loadBalancer: {}